fix indentation

diff --git a/clean-build.in b/clean-build.in
--- a/clean-build.in
+++ b/clean-build.in
@@ -2,8 +2,8 @@
 
 # Helper functions
 error() {
-	echo "ERROR: $1" >&2
-	exit 1
+    echo "ERROR: $1" >&2
+    exit 1
 }
 
 info() {
@@ -179,7 +179,7 @@ print_usage() {
 }
 
 print_help() {
-	cat <<EOF
+    cat <<EOF
 options:
     -v,--version   display version
     -h,--help       display this message
@@ -191,8 +191,8 @@ EOF
 parse_options() {
     EXTRA_OPTIONS=()
     
-	while [ "$1" ]; do
-		case $1 in
+    while [ "$1" ]; do
+        case $1 in
             -cf|--config-file)
                 if [ ! "$2" ]; then
                     error "$1 requires an argument"
@@ -210,15 +210,15 @@ parse_options() {
             -v|--version)
                 print_version
                 exit 0;;
-			-h|--help)
-				print_help
-				exit 0;;
-			*)
-				EXTRA_OPTIONS=(${EXTRA_OPTIONS[@]} $1)
-				;;
-		esac
+            -h|--help)
+                print_help
+                exit 0;;
+            *)
+                EXTRA_OPTIONS=(${EXTRA_OPTIONS[@]} $1)
+                ;;
+        esac
         shift
-	done
+    done
 }
 
 parse_action() {
@@ -247,7 +247,7 @@ main() {
         exit 1;
     fi
     
-	parse_options "$@"
+    parse_options "$@"
     load_file "$CB_CONFIG_FILE"
     parse_action
     
